### ISSUE TITLE
Compilation errors stop pojobuilder (3.4.0) execution

### ISSUE THREAD

**Issue by dsf001** [mkarneim/pojobuilder#109]
Having one valid compilation error (missing import) during maven build pojobuilder is not creating the builder classes and maven exits with showing compilation errors wherever the builder classes were referenced. Version 2.4.1 did not have this behaviour and showed the valid compilation error(s) only.

**Comment by mkarneim** [comment]
Ok, I guess you have to be more specific.

Please post the relevant code, the pom, and the error messages you get.
