### ISSUE TITLE
Setter with more then one argument

### ISSUE THREAD

**Issue by uvula** [mkarneim/pojobuilder#111]
Hello Michael,

I tried PB to generate fluent interface, but I have a question.
When a setter has more then one argument (eg.
    void setThreshold("A", 3);
there is no code generated in this case. But for the fluent interface is make sense to have it.
   new Builder().withThreshold("A", 3).build();

**Comment by tomasbjerre** [comment]
Can you also supply a the POJO that you want to build?

**Comment by mkarneim** [comment]
Hello uvula,

PojoBuilder only supports properties that have a single name and type.
Therefore PB ignores setter methods with more than one argument.

To solve this you could either split "threshold" into two separate properties or combine them into a custom class structure.

**Comment by mkarneim** [comment]
@uvula may I ask you to close this issue if you accept my answer?
