### ISSUE TITLE
NullPointerException while constructing processor

### ISSUE THREAD

**Issue by rwestgeest** [mkarneim/pojobuilder#114]
Hi, 

I inherited a project which I tried to build. It is using pojobiulder. I got this odd 

"Exception thrown while constructing Processor object: java.lang.NullPointerException" during mvn clean compile, which disappeared when removing pojobuilder from the pom (along with removing all of the annotations)

This is the section i remove:

``` xml
        <dependency>
            <groupId>net.karneim</groupId>
            <artifactId>pojobuilder</artifactId>
            <!-- 'provided' scope because this is only needed during compilation -->
            <scope>provided</scope>
        </dependency>
```

Removing the annotations without removing the section from the pom does not work. 

Do you have any idea how to debug this or what the issue might be ? 

Cheers.

Rob

**Comment by mkarneim** [comment]
Sorry, but I've got no idea.
Could you please post a complete but simplified POM that I can use to reproduce this issue?

**Comment by mkarneim** [comment]
@rwestgeest is this issue still relevant, or can it be closed?
