### ISSUE TITLE
Why is no optional method generated for primitive fields?

### ISSUE THREAD

**Issue by Adrodoc55** [mkarneim/pojobuilder#122]
For instance the class [PojoWithGuavaOptionalBuilder](https://github.com/mkarneim/pojobuilder/blob/master/src/testdata/java/net/karneim/pojobuilder/processor/with/optionals/PojoWithGuavaOptionalBuilder.java#L30-L34) could very well have this additional method:

``` java
/**
 * Optionally sets the default value for the {@link PojoWithGuavaOptional#boxedInt} property.
 *
 * @param optionalValue the default value
 * @return this builder
 */
public PojoWithGuavaOptionalBuilder withPrimitiveInt(Optional<Integer> optionalValue) {
  return optionalValue.isPresent()?withPrimitiveInt(optionalValue.get()):self;
}
```

The generation of such a method is prevented [here](https://github.com/mkarneim/pojobuilder/blob/master/src/main/java/net/karneim/pojobuilder/model/PropertyM.java#L70-L72).
For comparison, with-Builder methods are generated for primitive types as you can see in [PojoBuilder](https://github.com/mkarneim/pojobuilder/blob/master/src/testdata/java/net/karneim/pojobuilder/processor/with/builderinterface/PojoBuilder.java#L87-L97)

**Comment by mkarneim** [comment]
You are right.
I guess I just missed it when I merged this code into PB.
Feel free to fix it and send me some pull request.
;-)
