### ISSUE TITLE
Properties using Optional should have the type: Optional<? extends Type>

### ISSUE THREAD

**Issue by Adrodoc55** [mkarneim/pojobuilder#123]
For example, the generated builder for the following pojo is not correct:
```java
@GeneratePojoBuilder(withOptionalProperties = Optional.class)
public class Pojo {
  public Number value;
}
```
The optional-with-method "withValue" should have the following signature:
`public PojoBuilder withValue(Optional<? extends Number> value)`

but has:
`public PojoBuilder withValue(Optional<Number> value)`

This is similar to #115

**Comment by mkarneim** [comment]
Nice!
