### ISSUE TITLE
Support Setter Methods with return type

### ISSUE THREAD

**Issue by Adrodoc55** [mkarneim/pojobuilder#127]
PB does not generate with-Methods for Setter Methods that have a return type. Supporting these would not have negative side effects, because there can't be multiple methods that only differ in their return type and PB can ignored the return type.
This does not fit the Java Bean Specification, but suppressing the generation of certain with-Methods can easily be achieved with excludes.
The benefit is that PB can support more constructs, like setter methods that return their object in a fluent API, or Setter Methods that return whether they were successful.
I am not 100% sure if this should be supported, so please tell me what you think about this.

**Comment by mkarneim** [comment]
Sounds good to me.
I'll accept your pull request ;-)
