### ISSUE TITLE
Support Java 8 Supplier as withBuilderInterface

### ISSUE THREAD

**Issue by drekbour** [mkarneim/pojobuilder#133]
PBs should be capable of implementing `java.util.function.Supplier<T>`. Currently I need to write:
````java
/**
 * Supplier Facade for PojoBuilder.
 */
public interface SupplierBuilder<T> extends Supplier<T> {
    T build();

    default T get() {
        return build();
    }

    static <T> Collector<Supplier<T>, ?, List<T>> toSuppliedList() {
        return mapping(Supplier::get, toList());
    }

}
````
then give that as directive `withBuilderInterface = SupplierBuilder.class`

**Comment by mkarneim** [comment]
This looks perfectly good for me.
I would do it the same.

What exactly do you want to change about this?

**Comment by drekbour** [comment]
Users don't want to have to have to write facades for this, however small. The value of PB over, say, and IDE-generated builder is the depth of features that can be added "just work".

`withBuilderInterface = Supplier.class` either as a special case (this _is_ a language feature) or by generalising the `public T build()` check to `public T <anything>()`

**Comment by mkarneim** [comment]
Alright.
I will add support for 'builder' interfaces that hava a `get()` method as an alternative to `build()`.
