### ISSUE TITLE
Class-level annotation with one constructor no longer works

### ISSUE THREAD

**Issue by drekbour** [mkarneim/pojobuilder#135]
I've just noticed that PB has lost the ability to put `@GeneratePojoBuilder` at the class level where this is one constructor only. This is a common Value Object pattern so really should be supported as @GPB cannot be used as a meta-annotation 

````java
@GeneratePojoBuilder
public class ABC{
  private final String x;
  public ABC(String x) {
    this.x = x;
  }
  public String getX(){
    return x;
  }
}
````

PB 3.5.0 says:
>   Error:(58, 33) java: constructor ABC in class com.abc.ABC cannot be applied to given types;
>   required: java.lang.String
>   found: no arguments
>   reason: actual and formal argument lists differ in length

**Comment by mkarneim** [comment]
Alright, this is in the queue.
